registry = {
    "00": {
        "name": "tokenizer_00",
        "version": "00",
        "training_corpus": "00",
        "alphabet_size": 20,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "01": {
        "name": "tokenizer_01",
        "version": "01",
        "training_corpus": "00",
        "alphabet_size": 10,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "02": {
        "name": "tokenizer_02",
        "version": "02",
        "training_corpus": "00",
        "alphabet_size": 5,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "03": {
        "name": "tokenizer_03",
        "version": "03",
        "training_corpus": "00",
        "alphabet_size": 2,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "04": {
        "name": "tokenizer_04",
        "version": "04",
        "training_corpus": "00",
        "alphabet_size": 1,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "05": {
        "name": "tokenizer_05",
        "version": "05",
        "training_corpus": "02",
        "alphabet_size": 20,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "06": {
        "name": "tokenizer_06",
        "version": "06",
        "training_corpus": "02",
        "alphabet_size": 10,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "07": {
        "name": "tokenizer_07",
        "version": "07",
        "training_corpus": "02",
        "alphabet_size": 5,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "08": {
        "name": "tokenizer_08",
        "version": "08",
        "training_corpus": "02",
        "alphabet_size": 2,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
    "09": {
        "name": "tokenizer_09",
        "version": "09",
        "training_corpus": "02",
        "alphabet_size": 1,
        "type": "unigram",
        "normalization": "identity",
        "remove whitespace": "false",
        "split on whitespace": "false",
    },
}
