[project]
name = "proofread-eng-scify"
version = "0.1.0"
description = """
An artisanal language model for proofreading prose in the style of
classical English science fiction.
"""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sentencepiece>=0.2.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
