registry = {
    "00": {
        "version": "00",
        "name": "somm_00",
        "description": "2nd-order Markov",
        "epsilon": 1e-10,
        "probability_floor": 1e-9,
        "training_corpus": ["00"],
        "tokenizer_version": "04",
    },
    "01": {
        "version": "01",
        "name": "somm_01",
        "description": "2nd-order Markov",
        "epsilon": 1e-10,
        "probability_floor": 1e-9,
        "training_corpus": ["00", "01"],
        "tokenizer_version": "04",
    },
    "02": {
        "version": "02",
        "name": "somm_02",
        "description": "sparse 2nd-order Markov",
        "epsilon": 1e-10,
        "probability_floor": 1e-9,
        "training_corpus": ["00", "01"],
        "tokenizer_version": "00",
    },
    "03": {
        "version": "03",
        "name": "somm_03",
        "description": "sparse 2nd-order Markov",
        "epsilon": 1e-10,
        "probability_floor": 1e-9,
        "training_corpus": ["02"],
        "tokenizer_version": "05",
    },
    "04": {
        "version": "04",
        "name": "somm_04",
        "description": "sparse 2nd-order Markov",
        "epsilon": 1e-10,
        "probability_floor": 1e-9,
        "training_corpus": ["02"],
        "tokenizer_version": "06",
    },
    "05": {
        "version": "05",
        "name": "somm_05",
        "description": "sparse 2nd-order Markov",
        "epsilon": 1e-10,
        "probability_floor": 1e-9,
        "training_corpus": ["02"],
        "tokenizer_version": "07",
    },
    "06": {
        "version": "06",
        "name": "somm_06",
        "description": "sparse 2nd-order Markov",
        "epsilon": 1e-10,
        "probability_floor": 1e-9,
        "training_corpus": ["02"],
        "tokenizer_version": "08",
    },
    "07": {
        "version": "07",
        "name": "somm_07",
        "description": "sparse 2nd-order Markov",
        "epsilon": 1e-10,
        "probability_floor": 1e-9,
        "training_corpus": ["02"],
        "tokenizer_version": "09",
    },
}
